### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by q2dg** [INEXTH/Arduino-ESP8266_libs#4]
Thanks

**Comment by auveele** [comment]
No, I'm not going to maintain this library.
I only fork it, to modify something that didn't work in my project.

I'm not an expert, but I could try to help you if you need something.
Thank you for asking.

**Comment by q2dg** [comment]
Oh well, I wouldn't like to bother you, never mind.
Thanks a lot anyway!!
I close the issue
